# Generated by Django 4.2 on 2024-10-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='course_images/')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('question_es', models.CharField(max_length=255, null=True)),
                ('question_fr', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_en', models.TextField(null=True)),
                ('answer_es', models.TextField(null=True)),
                ('answer_fr', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='feedback_images/')),
                ('comment', models.TextField()),
                ('comment_en', models.TextField(null=True)),
                ('comment_es', models.TextField(null=True)),
                ('comment_fr', models.TextField(null=True)),
                ('profession', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='mentor_images/')),
                ('experience', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OurProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ImageField(upload_to='our_program_logs/')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_es', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partner_images/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='why_us_images/')),
                ('title', models.CharField(max_length=250)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('title_es', models.CharField(max_length=250, null=True)),
                ('title_fr', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContactAplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saidoff_academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='OurProgramInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('our_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saidoff_academy.ourprogram')),
            ],
        ),
        migrations.CreateModel(
            name='MentorWorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='workplace_logos/')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saidoff_academy.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saidoff_academy.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='ForWhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saidoff_academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration', models.CharField(max_length=100)),
                ('time_for_theory', models.CharField(max_length=100)),
                ('time_for_practice', models.CharField(max_length=100)),
                ('for_theory', models.TextField()),
                ('for_practice', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saidoff_academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saidoff_academy.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saidoff_academy.coursemodule')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('video_card', models.CharField(max_length=100)),
                ('screen', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saidoff_academy.course')),
            ],
        ),
    ]
