# Generated by Django 4.2 on 2024-10-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saidoff_academy', '0002_alter_mentor_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='saidoff_academy.course'),
        ),
    ]
