# Generated by Django 4.2 on 2024-10-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saidoff_academy', '0003_alter_mentor_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='extra_field',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='number_of_projects',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='number_of_video_lessons',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computerfeatures',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_features', to='saidoff_academy.course'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='course_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='saidoff_academy.coursemodule'),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='saidoff_academy.course'),
        ),
        migrations.AlterField(
            model_name='courseplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_plans', to='saidoff_academy.course'),
        ),
        migrations.AlterField(
            model_name='forwhom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_whoms', to='saidoff_academy.course'),
        ),
        migrations.AlterField(
            model_name='mentorworkplace',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_work_places', to='saidoff_academy.mentor'),
        ),
        migrations.AlterField(
            model_name='usercontactaplication',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact_aplications', to='saidoff_academy.course'),
        ),
        migrations.DeleteModel(
            name='MentorAchievements',
        ),
    ]
